version: '2'

services:
  datastore:
    image: busybox
    volumes:
     - /var/lib/mysql
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8
    env_file: .env
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes_from:
      - datastore
  redis:
    image: redis:3.2.3-alpine
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
  app:
    build: ./docker/app
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/app/000-default.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - db
      - redis
